const {chromium} = require('playwright');
const {spawn} = require('node:child_process');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), assert = require('node:assert/strict');
const proc = spawn(process.env.PYTHON || 'python', ['-X','utf8',path.join(__dirname,'recovery_e2e_server.py')], {windowsHide:true});
let context;
(async()=>{
  const info = await new Promise((resolve,reject)=>{let data=''; proc.stdout.on('data',b=>{data+=b; if(data.includes('\n'))resolve(JSON.parse(data.split('\n')[0]));});proc.on('error',reject);proc.stderr.on('data',b=>process.stderr.write(b));});
  const base = `http://127.0.0.1:${info.port}`;
  const identity = process.env.E2E_HISTORY_IDENTITY === '1';
  const extension = path.resolve(__dirname,'../chrome_extension');
  context = await chromium.launchPersistentContext('',{headless:true,channel:'chromium',viewport:{width:440,height:1050},acceptDownloads:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
  const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  await worker.evaluate(baseUrl=>chrome.storage.sync.set({loraManagerBaseUrl:baseUrl}),base);
  // A real Chrome completed-download record in a non-default folder, without an armed wait.
  const custom = path.join(info.root,'CustomDownloads');fs.mkdirSync(custom);
  const downloadPage = await context.newPage();
  const cdp = await context.newCDPSession(downloadPage);
  await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:custom,eventsEnabled:true});
  const h=Buffer.from(JSON.stringify({'__metadata__':{'ss_network_module':'networks.lora','modelspec.title':'History fixture'}}));
  const n=Buffer.alloc(8);n.writeBigUInt64LE(BigInt(h.length));const bytes=identity ? fs.readFileSync(path.join(info.root,'history-fixture.bin')) : Buffer.concat([n,h,Buffer.alloc(16)]);
  await context.route('https://recovery.fixture.invalid/**',r=>r.fulfill({contentType:'application/octet-stream',headers:{'Content-Disposition':'attachment; filename="history.safetensors"'},body:bytes}));
  if(identity) await context.route('https://civitai.red/api/download/models/3292162',r=>r.fulfill({contentType:'application/octet-stream',headers:{'Content-Disposition':'attachment; filename="history.safetensors"'},body:bytes}));
  const downloadPromise=downloadPage.waitForEvent('download');
  await downloadPage.goto(identity ? 'https://civitai.red/api/download/models/3292162' : 'https://recovery.fixture.invalid/model.safetensors').catch(()=>{});
  const dl=await downloadPromise;assert.equal(await dl.failure(),null);
  assert.equal(fs.existsSync(path.join(custom,'history.safetensors')),true);
  const history=await worker.evaluate(()=>chrome.downloads.search({state:'complete'}));
  assert.ok(history.some(x=>x.filename.endsWith('history.safetensors')));
  assert.equal((await(await fetch(base+'/api/lora/pending-download')).json()).pending,null);
  const extensionId=new URL(worker.url()).host;
  let popup=await context.newPage();
  const errors=[];popup.on('pageerror',e=>errors.push(e.message));
  await popup.goto(`chrome-extension://${extensionId}/popup.html`);
  await popup.waitForFunction(()=>!state.recoveryRefreshing);
  await popup.locator('#recover-downloads').click();
  await popup.waitForFunction(()=>state.recoveryRunning);
  assert.equal(await popup.locator('#recover-downloads').isDisabled(),true);
  const current=await(await fetch(base+'/api/lora/recover-downloads')).json();
  assert.equal(current.status,'running');
  await popup.close();
  let result;
  const deadline=Date.now()+15000;
  do { await new Promise(r=>setTimeout(r,150));result=await(await fetch(base+'/api/lora/recover-downloads')).json(); } while(result.status==='running'&&Date.now()<deadline);
  assert.equal(result.status,'complete',JSON.stringify(result));
  assert.equal(result.imported,2,JSON.stringify(result));
  assert.equal(result.skipped,1);
  assert.equal(fs.existsSync(info.direct),false);
  assert.equal(fs.existsSync(path.join(custom,'history.safetensors')),false);
  assert.deepEqual(fs.readFileSync(path.join(identity ? info.checkpoints : info.models,'history.safetensors')),bytes);
  assert.equal(fs.existsSync(path.join(info.root,'Downloads','ordinary.json')),true);
  popup=await context.newPage();popup.on('pageerror',e=>errors.push(e.message));
  await popup.goto(`chrome-extension://${extensionId}/popup.html`);
  await popup.waitForFunction(()=>document.querySelector('#recovery-status').textContent.includes('登録・移動 2件'));
  assert.match(await popup.locator('#recovery-results').textContent(),/history.safetensors/);
  await popup.screenshot({path:process.env.E2E_SCREENSHOT || path.join(os.tmpdir(),'bridge-recovery-verified.png'),fullPage:true});
  console.log('PASS real MV3 popup button, Chrome completion history, Downloads scan, close/reopen progress, byte-identical move and ordinary JSON exclusion');
  await popup.locator('#recover-downloads').click();
  await popup.waitForFunction(()=>document.querySelector('#recovery-status').textContent.includes('登録・移動 0件') && !state.recoveryRunning);
  assert.equal(fs.readdirSync(info.models).filter(n=>n.endsWith('.safetensors')).length,identity ? 1 : 2);
  if(identity) console.log('PASS unknown Anima checkpoint matched by real Chrome version URL and local SHA-256 despite different published filename');
  assert.deepEqual(errors,[]);
  console.log('PASS repeat click imports zero duplicates; popup JavaScript has no errors');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(context)await context.close();proc.stdin.end('\n');});
